services:
  client:
    build:
      context: .
    container_name: client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_BASE_URL=${API_BASE_URL}
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
      - PROJECT_NAME=${PROJECT_NAME}
    volumes:
      - ./src:/application/src
      - ./server:/application/server
      - ./public:/application/public
      - next-cache:/application/.next
    restart: unless-stopped

volumes:
  next-cache:
