export enum IssueReasonTypesEnum {
    USER = 'user',
    ORDER = 'order',
    ORDER_EXPENSE = 'order_expense',
    ORDER_VEHICLE = 'order_vehicle',
    ORDER_INTERNAL_NOTE = 'order_internal_note',
    ORDER_INSPECTION = 'order_inspection',
    ORDER_INSPECTION_PHOTO = 'order_inspection_photo',
    ORDER_INSPECTION_SCHEMATIC_PHOTO = 'order_inspection_schematic_photo',
    ORDER_BOL = 'order_bol',
    CHAT_MESSAGE = 'chat_message',
    ORDER_INVOICE = 'order_invoice',
    SIGNATURE = 'signature',
    COMPANY = 'company',
    ACCOUNT = 'account',
    INVITATION = 'invitation',
    JOB_OFFER = 'job_offer',
    ACCOUNTING_PROFILE_DOCUMENT = 'accounting_profile_document',
    ACCOUNTING_PROFILE = 'accounting_profile',
    BALANCE = 'balance',
    ORDER_REQUESTED_DOCUMENT = 'order_requested_document',
    FEE = 'fee',
}
