export enum PaymentConfirmationType {
    ADJUSTMENT_TRANSACTION = 'adjustment_transaction',
    FUEL_CARD_TRANSACTION = 'fuel_card_transaction',
    MANUAL_TRANSACTION = 'manual_transaction',
    ORDER_HOLD_BROKER_FEE = 'order_hold_broker_fee',
    ORDER_PAYMENT_CONFIRMED_DISPATCH = 'order_payment_confirmed_dispatch',
    ORDER_HOLD_FUNDS_DISPATCH = 'order_hold_funds_dispatch',
    ORDER_PAYMENT_CONFIRMED_FACTORING = 'order_payment_confirmed_factoring',
    ORDER_HOLD_FUNDS_FACTORING = 'order_hold_funds_factoring',
    ORDER_PAYMENT_CONFIRMED_USHIPPER = 'order_payment_confirmed_ushipper',
    ORDER_HOLD_FUNDS_USHIPPER = 'order_hold_funds_ushipper',
    ORDER_COD_WALLET_TOP_UP = 'order_cod_wallet_top_up',
    ORDER_PAYMENT_CONFIRMED_DRIVER = 'order_payment_confirmed_driver',
    ORDER_PAYMENT_CONFIRMED_CHECK = 'order_payment_confirmed_check',
    ORDER_COD_DELAYED_DRIVER_PAYMENT = 'order_cod_delayed_driver_payment',
    ORDER_DELAYED_PAYMENT_TO_WALLET = 'order_delayed_payment_to_wallet',
    ORDER_INSTANT_PAYMENT_TO_WALLET = 'order_instant_payment_to_wallet',
    RECURRING_TRANSACTION = 'recurring_transaction',
    ROLLBACK_TRANSACTION = 'rollback_transaction',
}
