export enum OrderStatisticsStatus {
    NEW = 'new',
    STATUS_NEW = 'status_new',
    ON_HOLD = 'on_hold',
    POSTED = 'posted',
    PENDING = 'pending',
    DECLINED = 'declined',
    ACCEPTED = 'accepted',
    INVOICED = 'invoiced',
    ASSIGNED = 'assigned',
    PICKED_UP = 'picked_up',
    DELIVERED = 'delivered',
    UNDELIVERED = 'undelivered',
    FUNDS_TRANSFERRED = 'funds_transferred',
    FUNDS_PENDING = 'funds_pending',
    FUNDS_CLAIMED = 'funds_claimed',
    FUNDS_PENDING_DOCUMENTS = 'funds_pending_documents',
    BILLED = 'billed',
    PAID = 'paid',
    ARCHIVED = 'archived',
    DELETED = 'deleted',
    CANCELLED = 'cancelled',
    FLAGGED = 'flagged',
    REQUESTED = 'requested',
    USED_FOR_FUEL_CARDS = 'used_for_fuel_cards',
    HAS_BALANCE_HOLD = 'has_balance_hold',
}
