export enum BusinessTypesEnum {
    AUCTION = 'Auction',
    AUCTION_DEALER = 'Auction / Dealer',
    BROKER = 'Broker',
    BROKER_CARRIER = 'Broker / Carrier',
    CORP_RELOCATION = 'Corp. Relocation',
    DEALER = 'Dealer',
    DEALER_IMPORT_EXPORT = 'Dealer / Import/Export',
    DEALER_MANUFACTURER = 'Dealer / Manufacturer',
    DEALER_RENTAL_AGENCY = 'Dealer / Rental Agency',
    DEALER_SALVAGE = 'Dealer / Salvage',
    IMPORT_EXPORT = 'Import/Export',
    MANUFACTURER = 'Manufacturer',
    RENTAL_AGENCY = 'Rental Agency',
    SALVAGE = 'Salvage',
    IMPORT_EXPORT_SALVAGE = 'Import / Export / Salvage',
    SHIPPER = 'shipper',
    CARRIER = 'Carrier',
}
