export enum DamageCode {
    BROKEN = 'broken',
    CHIPPED = 'chipped',
    CRACKED = 'cracked',
    DENTED = 'dented',
    FADED = 'faded',
    FOREIGN_FLUID = 'foreign-fluid',
    FLAT_TIRE = 'flat-tire',
    GOUGE = 'gouge',
    HAIL_DAMAGE = 'hail-damage',
    LOOSE_CONTENTS = 'loose-contents',
    MISSING = 'missing',
    MAJOR_DAMAGE = 'major-damage',
    MULTIPLE_SCRATCHES = 'multiple-scratches',
    OTHER = 'other',
    PAINT_CHIP = 'paint-chip',
    RUBBED = 'rubbed',
    RUST = 'rust',
    SCRATCHED = 'scratched',
    SCUFFED = 'scuffed',
}
