export enum VehicleType {
    SEDAN = 'sedan',
    COUPE_TWO_DOORS = 'coupe_two_doors',
    SUV = 'suv',
    PICKUP_TWO_DOORS = 'pickup_two_doors',
    PICKUP_FOUR_DOORS = 'pickup_four_doors',
    VAN_TRUCK_DAYCAB = 'van_truck_daycab',
    TRUCK_WITH_SLEEPER = 'truck_with_sleeper',
    MOTORCYCLE = 'motorcycle',
    BOAT = 'boat',
    RV = 'rv',
    HEAVY_MACHINERY = 'heavy_machinery',
    FREIGHT = 'freight',
    LIVESTOCK = 'livestock',
    ATV = 'atv',
    TRAILER_BUMPER_PULL = 'trailer_bumper_pull',
    TRAILER_GOOSENECK = 'trailer_gooseneck',
    TRAILER_5TH_WHEEL = 'trailer_5th_wheel',
    OTHER = 'other',
}
