import { translateByNamespace } from '@utils/i18n';

export const t = translateByNamespace('common:create-update-role-block');
const shipperTranslate = translateByNamespace('common:create-update-role-block.shipper');
const administrationTranslate = translateByNamespace('common:create-update-role-block.administration');

export const CarrierRoleTypesMap: Record<string, string> = {
    carrierOwner: t('carrier-owner-role-type'),
    carrierAdmin: t('carrier-admin-role-type'),
    carrierDispatcher: t('carrier-dispatcher-role-type'),
    carrierDriver: t('carrier-driver-role-type'),
};

export const ShipperRoleTypesMap: Record<string, string> = {
    shipperAdmin: t('shipper:shipper-admin-role-type'),
    shipperDispatcher: t('shipper:shipper-dispatcher-role-type'),
    shipperManager: t('shipper:shipper-manager-role-type'),
    shipperOwner: t('shipper:shipper-owner-role-type'),
};

export const AdminRoleTypesMap: Record<string, string> = {
    admin: administrationTranslate('admin-role-type'),
    superAdmin: administrationTranslate('admin-super-admin-role-type'),
};

export const ClientPermissionGroupsMap: Record<string, string> = {
    carrierOrders: t('carrier-permissions-group-order'),
    shipperOrders: shipperTranslate('permissions-group-order'),
    shipperAdministration: shipperTranslate('permissions-group-administration'),
    carrierAdministration: t('carrier-permissions-group-administration'),
    mobileApp: t('carrier-permissions-group-mobile-app'),
};

export const AdminPermissionGroupsMap: Record<string, string> = {
    adminPanel: administrationTranslate('admin-permissions-group-panel'),
    adminPanelAdministration: administrationTranslate('admin-permissions-group-panel-administration'),
    adminPanelSettings: administrationTranslate('admin-permissions-group-panel-settings'),
    adminPanelAccounting: administrationTranslate('admin-permissions-group-panel-accounting'),
    adminPanelFees: administrationTranslate('admin-permissions-group-panel-fees'),
    adminPanelNotifications: administrationTranslate('admin-permissions-group-panel-notifications'),
    fuelCards: administrationTranslate('admin-permissions-group-panel-fuel'),
};

export const CarrierPermissionsMap: Record<string, string> = {
    'carrier.orders.view_any': t('carrier-order-list-permission'),
    'carrier.orders.create': t('carrier-order-create-permission'),
    'carrier.orders.update': t('carrier-order-edit-permission'),
    'carrier.orders.archive': t('carrier-order-archive-permission'),
    'carrier.orders.delete': t('carrier-order-delete-permission'),
    'carrier.orders.restore': t('carrier-order-restore-permission'),
    'carrier.orders.set_driver': t('carrier-order-set-driver-permission'),
    'carrier.orders.set_dispatcher': t('carrier-order-set-dispatcher-permission'),
    'carrier.orders.send_invoice': t('carrier-order-send-invoice-permission'),
    'carrier.orders.send_bol': t('carrier-order-send-bol-permission'),
    'carrier.orders.mark_as_paid': t('carrier-order-mark-as-paid-permission'),
    'carrier.orders.internal_notes.view_any': t('carrier-order-internal-notes-permission'),
    'carrier.orders.expenses.view_any': t('carrier-order-expenses-permission'),
    'carrier.orders.attachments.view_any': t('carrier-order-attachments-permission'),
    'carrier.orders.bols.view_any': t('carrier-order-bols-permission'),
    'carrier.orders.inspections.view_any': t('carrier-order-inspections-permission'),
    'carrier.orders.activity.view_any': t('carrier-order-activity-permission'),
    'carrier.orders.offers.view_any': t('carrier-order-offer-list-permission'),
    'carrier.orders.offers.accept': t('carrier-order-offer-accept-permission'),
    'carrier.orders.offers.decline': t('carrier-order-offer-decline-permission'),
    'carrier.orders.requests.view_any': t('carrier-order-requests-permission'),
    'carrier.contacts.view_any': t('carrier-contacts-permission'),
    'carrier.tracking.view_any': t('carrier-tracking-permission'),
    'carrier.reviews.view_any': t('carrier-reviews-permission'),
    'carrier.reviews.create': t('carrier-reviews-create-permission'),
    'carrier.reviews.update': t('carrier-reviews-update-permission'),
    'carrier.reviews.replies.create': t('carrier-replies-reviews-create-permission'),
    'carrier.reviews.replies.update': t('carrier-replies-reviews-update-permission'),
    'carrier.order_board.available_orders.view_any': t('carrier-order-board-available-orders-permission'),
    'carrier.administration.staff.view_any': t('carrier-administration-staff-permission'),
    'carrier.administration.role_settings.view_any': t('carrier-administration-role-settings-permission'),
    'carrier.administration.company_settings.view_any': t('carrier-administration-company-settings-permission'),
    'carrier.mobile_app.orders.order_board.view_any': t('mobile-app.orders-order-board-permission'),
    'carrier.mobile_app.orders.pickup_information.update': t('mobile-app.orders-pickup-information-update-permission'),
    'carrier.mobile_app.orders.delivery_information.update': t('mobile-app.orders-delivery-information-update-permission'),
    'carrier.mobile_app.orders.customer_information.update': t('mobile-app.orders-customer-information-update-permission'),
    'carrier.mobile_app.orders.payment_information.update': t('mobile-app.orders-payment-information-update-permission'),
    'carrier.mobile_app.orders.expenses_information.update': t('mobile-app.orders-expenses-update-permission'),
    'carrier.mobile_app.orders.vehicles_information.update': t('mobile-app.orders-vehicles-update-permission'),
    'carrier.mobile_app.orders.attachments_information.update': t('mobile-app.orders-attachments-update-permission'),
    'carrier.mobile_app.orders.send_invoice': t('mobile-app.orders-send-invoice-permission'),
    'carrier.mobile_app.orders.send_bol': t('mobile-app.orders-send-bol-permission'),
    'carrier.mobile_app.orders.mark_as_paid': t('mobile-app.orders-mark-as-paid-permission'),
    'carrier.mobile_app.offers.view_any': t('mobile-app.offer-list-permission'),
    'carrier.mobile_app.user.delete_yourself': t('mobile-app.user-delete-yourself'),
    'carrier.mobile_app.orders.delete': t('mobile-app.orders-delete'),
    'carrier.mobile_app.orders.archive': t('mobile-app.orders-archive'),
    'carrier.mobile_app.orders.sign': t('mobile-app.orders-sign'),
    'carrier.mobile_app.orders.inspections.update': t('mobile-app.orders-inspections-update'),
};

export const ShipperPermissionsMap: Record<string, string> = {
    'shipper.my_orders.all_orders.view_any': shipperTranslate('all-orders-permission'),
    'shipper.my_orders.all_orders.send_offer': shipperTranslate('offer-send-permission'),
    'shipper.my_orders.all_orders.post_to_order_board': shipperTranslate('post-to-order-board-permission'),
    'shipper.my_orders.all_orders.delete_from_order_board': shipperTranslate('delete-from-order-board-permission'),
    'shipper.my_orders.all_orders.update': shipperTranslate('order-edit-permission'),
    'shipper.my_orders.all_orders.delete': shipperTranslate('order-delete-permission'),
    'shipper.my_orders.all_orders.archive': shipperTranslate('order-archive-permission'),
    'shipper.my_orders.all_orders.restore': shipperTranslate('order-restore-permission'),
    'shipper.my_orders.all_orders.set_dispatcher': shipperTranslate('order-set-dispatcher-permission'),
    'shipper.my_orders.all_orders.send_invoice': shipperTranslate('order-send-invoice-permission'),
    'shipper.my_orders.all_orders.send_bol': shipperTranslate('order-send-bol-permission'),
    'shipper.my_orders.contacts.view_any': shipperTranslate('contacts-list-permission'),
    'shipper.my_orders.contacts.create': shipperTranslate('contacts-create-permission'),
    'shipper.my_orders.contacts.update': shipperTranslate('contacts-edit-permission'),
    'shipper.my_orders.contacts.delete': shipperTranslate('contacts-delete-permission'),
    'shipper.my_orders.offers.view_any': shipperTranslate('offer-list-permission'),
    'shipper.my_orders.offers.delete': shipperTranslate('offer-delete-permission'),
    'shipper.my_orders.reports.view_any': shipperTranslate('reports-permission'),
    'shipper.my_orders.requests.view_any': shipperTranslate('requests-permission'),
    'shipper.my_orders.internal_notes.view_any': shipperTranslate('internal-notes-permission'),
    'shipper.my_orders.internal_notes.create': shipperTranslate('internal-notes-create-permission'),
    'shipper.my_orders.internal_notes.update': shipperTranslate('internal-notes-edit-permission'),
    'shipper.my_orders.internal_notes.delete': shipperTranslate('internal-notes-delete-permission'),
    'shipper.my_orders.history_items.view_any': shipperTranslate('history-items-permission'),
    'shipper.my_orders.attachments.view_any': shipperTranslate('attachments-permission'),
    'shipper.my_orders.attachments.create': shipperTranslate('attachments-create-permission'),
    'shipper.my_orders.attachments.delete': shipperTranslate('attachments-delete-permission'),
    'shipper.my_orders.inspections.view_any': shipperTranslate('inspections-view_any'),
    'shipper.my_orders.bols.view_any': shipperTranslate('bols-permission'),
    'shipper.tracking.view_any': shipperTranslate('tracking-permission'),
    'shipper.order_board.available_orders.view_any': shipperTranslate('order-board-available-orders-permission'),
    'shipper.administration.staff.view_any': shipperTranslate('administration-staff-permission'),
    'shipper.administration.staff.create': shipperTranslate('administration-staff-create-permission'),
    'shipper.administration.staff.update': shipperTranslate('administration-staff-edit-permission'),
    'shipper.administration.staff.delete': shipperTranslate('administration-staff-delete-permission'),
    'shipper.administration.role_settings.view_any': shipperTranslate('administration-role-settings-permission'),
    'shipper.administration.role_settings.view': shipperTranslate('administration-role-settings-view-permission'),
    'shipper.administration.role_settings.create': shipperTranslate('administration-role-settings-create-permission'),
    'shipper.administration.role_settings.update': shipperTranslate('administration-role-settings-edit-permission'),
    'shipper.administration.role_settings.delete': shipperTranslate('administration-role-settings-delete-permission'),
    'shipper.administration.company_settings.view_any': shipperTranslate('administration-company-settings-permission'),
    'shipper.administration.company_settings.create': shipperTranslate('administration-company-settings-create-permission'),
    'shipper.administration.company_settings.update': shipperTranslate('administration-company-settings-edit-permission'),
    'shipper.administration.company_settings.delete': shipperTranslate('administration-company-settings-delete-permission'),
    'shipper.reviews.create': shipperTranslate('reviews-create'),
    'shipper.reviews.update': shipperTranslate('reviews-update'),
    'shipper.reviews.replies.create': shipperTranslate('replies-reviews-create'),
    'shipper.reviews.replies.update': shipperTranslate('replies-reviews-update'),
};

export const ClientPermissionMap = { ...CarrierPermissionsMap, ...ShipperPermissionsMap };

export const AdminPermissionsMap: Record<string, string> = {
    'admin_panel.accounting.view_any': administrationTranslate('admin-panel-accounting-permissions'),
    'admin_panel.orders.view_any': administrationTranslate('admin-orders-permission'),
    'admin_panel.orders.actions': administrationTranslate('admin-orders-actions-permission'),
    'admin_panel.companies.view_any': administrationTranslate('admin-companies-permission'),
    'admin_panel.companies.actions': administrationTranslate('admin-companies-actions-permission'),
    'admin_panel.contacts.view_any': administrationTranslate('admin-contacts-permission'),
    'admin_panel.users.view_any': administrationTranslate('admin-users-permission'),
    'admin_panel.users.actions': administrationTranslate('admin-users-actions-permission'),
    'admin_panel.tracking.view_any': administrationTranslate('admin-tracking-permission'),
    'admin_panel.administration.administrators.view_any': administrationTranslate('admin-administration-administrators-permission'),
    'admin_panel.administration.roles.view_any': administrationTranslate('admin-administration-roles-permission'),
    'admin_panel.settings.car_makers.view_any': administrationTranslate('admin-settings-car-makers-permission'),
    'admin_panel.settings.cars_models.view_any': administrationTranslate('admin-settings-car-models-permission'),
    'admin_panel.settings.preferences.view_any': administrationTranslate('admin-settings-preferences-permission'),
    'admin_panel.black_list_items.view_any': administrationTranslate('admin-black-list-permission'),
    'common.administration.job_offer.view_any': administrationTranslate('job-offer-permission'),
    'common.administration.job_offer.create': administrationTranslate('job-offer-create-permission'),
    'common.administration.job_offer.update': administrationTranslate('job-offer-update-permission'),
    'common.administration.webhook.view_any': administrationTranslate('webhook-permission'),
    'common.administration.webhook.create': administrationTranslate('webhook-create-permission'),
    'common.administration.webhook.delete': administrationTranslate('webhook-delete-permission'),
    'admin_panel.fees.view_any': administrationTranslate('admin-settings-fees-permission'),
    'admin_panel.issues.view_any': administrationTranslate('admin-issues-permission'),
    'admin_panel.chats.view_any': administrationTranslate('admin-chats-permission'),
    'admin_panel.loadboard.view_any': administrationTranslate('admin-loadboard-permission'),
    'admin_panel.notifications.account_created': administrationTranslate('admin-notifications-account-created-permission'),
    'admin_panel.notifications.balance_created': administrationTranslate('admin-notifications-balance-created-permission'),
    'admin_panel.notifications.cash_in_transaction_created': administrationTranslate('admin-notifications-cash-in-transaction-created-permission'),
    'admin_panel.notifications.cash_out_transaction_created': administrationTranslate('admin-notifications-cash-out-transaction-created-permission'),
    'admin_panel.notifications.twilio_exception': administrationTranslate('admin-notifications-twilio-exception-permission'),
    'admin_panel.notifications.instant_payment_requested': administrationTranslate('admin-notifications-instant-payment-requested-permission'),
    'admin_panel.notifications.issue_created': administrationTranslate('admin-notifications-issue-created-permission'),
    'admin_panel.transactions.view_any': administrationTranslate('admin-transactions-permission'),
    'admin_panel.transactions.actions': administrationTranslate('admin-transactions-actions-permission'),
    'admin_panel.wallets.factoring': administrationTranslate('admin-wallets-factoring-permission'),
    'admin_panel.wallets.ushipper': administrationTranslate('admin-wallets-ushipper-permission'),
    'admin_panel.wallets.dispatch': administrationTranslate('admin-wallets-dispatch-permission'),
    'admin_panel.wallets.broker': administrationTranslate('admin-wallets-broker-permission'),
    'admin_panel.wallets.cod': administrationTranslate('admin-wallets-cod-permission'),
    'admin_panel.wallets.custom_wallets': administrationTranslate('admin-wallets-custom-permission'),
    'admin_panel.accounting.cod_cop_orders': administrationTranslate('admin-accounting-cod-cop-orders-permission'),
    'admin_panel.carriers.view_any': administrationTranslate('admin-carriers-permission'),
    'admin_panel.carriers.actions': administrationTranslate('admin-carriers-actions-permission'),
    'admin_panel.drivers.view_any': administrationTranslate('admin-drivers-permission'),
    'admin_panel.drivers.actions': administrationTranslate('admin-drivers-actions-permission'),
    'admin_panel.fuel_cards.cards.view_any': administrationTranslate('admin-fuel-cards-permission'),
    'admin_panel.fuel_cards.cards.actions': administrationTranslate('admin-fuel-cards-actions-permission'),
    'admin_panel.fuel_cards.transactions.view_any': administrationTranslate('admin-fuel-cards-transactions-permission'),
    'admin_panel.fuel_cards.transactions.actions': administrationTranslate('admin-fuel-cards-transactions-actions-permission'),
};
